// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Espejo de BiometricResult.code. Se transporta como string para no acoplar
/// el enum de Dart al orden de los enums nativos.
class BiometricResultDto {
  BiometricResultDto({
    required this.code,
    this.reason,
  });

  String code;

  String? reason;

  Object encode() {
    return <Object?>[
      code,
      reason,
    ];
  }

  static BiometricResultDto decode(Object result) {
    result as List<Object?>;
    return BiometricResultDto(
      code: result[0]! as String,
      reason: result[1] as String?,
    );
  }
}

class BiometricAvailabilityDto {
  BiometricAvailabilityDto({
    required this.type,
    required this.status,
    required this.isEnrolled,
    required this.isLockedOut,
  });

  String type;

  String status;

  bool isEnrolled;

  bool isLockedOut;

  Object encode() {
    return <Object?>[
      type,
      status,
      isEnrolled,
      isLockedOut,
    ];
  }

  static BiometricAvailabilityDto decode(Object result) {
    result as List<Object?>;
    return BiometricAvailabilityDto(
      type: result[0]! as String,
      status: result[1]! as String,
      isEnrolled: result[2]! as bool,
      isLockedOut: result[3]! as bool,
    );
  }
}

/// Espejo de BiometricPolicy.Decision. La política vive en nativo: Flutter solo
/// recibe la decisión ya tomada.
class BiometricDecisionDto {
  BiometricDecisionDto({
    required this.kind,
    this.remaining,
    this.reason,
  });

  String kind;

  int? remaining;

  String? reason;

  Object encode() {
    return <Object?>[
      kind,
      remaining,
      reason,
    ];
  }

  static BiometricDecisionDto decode(Object result) {
    result as List<Object?>;
    return BiometricDecisionDto(
      kind: result[0]! as String,
      remaining: result[1] as int?,
      reason: result[2] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BiometricResultDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is BiometricAvailabilityDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is BiometricDecisionDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return BiometricResultDto.decode(readValue(buffer)!);
      case 130: 
        return BiometricAvailabilityDto.decode(readValue(buffer)!);
      case 131: 
        return BiometricDecisionDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BiometricCoreHostApi {
  /// Constructor for [BiometricCoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BiometricCoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<BiometricAvailabilityDto> availability() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.availability$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricAvailabilityDto?)!;
    }
  }

  /// Prompt crudo, sin política. Útil para casos especiales; para login usar runSession.
  Future<BiometricResultDto> authenticate(String reason, bool allowPinFallback) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.authenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[reason, allowPinFallback]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricResultDto?)!;
    }
  }

  /// Ejecuta un intento de BiometricSession nativo (disponibilidad, prompt y política).
  Future<BiometricDecisionDto> runSession(String reason, int maxAttempts) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.runSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[reason, maxAttempts]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricDecisionDto?)!;
    }
  }

  /// Reinicia el contador de intentos de la sesión nativa.
  Future<void> resetSession() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.resetSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
