// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Espejo de BiometricResult.code. Se transporta como string para no acoplar
/// el enum de Dart al orden de los enums nativos.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BiometricResultDto {
  var code: String
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricResultDto? {
    let code = pigeonVar_list[0] as! String
    let reason: String? = nilOrValue(pigeonVar_list[1])

    return BiometricResultDto(
      code: code,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      reason,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricAvailabilityDto {
  var type: String
  var status: String
  var isEnrolled: Bool
  var isLockedOut: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricAvailabilityDto? {
    let type = pigeonVar_list[0] as! String
    let status = pigeonVar_list[1] as! String
    let isEnrolled = pigeonVar_list[2] as! Bool
    let isLockedOut = pigeonVar_list[3] as! Bool

    return BiometricAvailabilityDto(
      type: type,
      status: status,
      isEnrolled: isEnrolled,
      isLockedOut: isLockedOut
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      status,
      isEnrolled,
      isLockedOut,
    ]
  }
}

/// Espejo de BiometricPolicy.Decision. La política vive en nativo: Flutter solo
/// recibe la decisión ya tomada.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BiometricDecisionDto {
  var kind: String
  var remaining: Int64? = nil
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricDecisionDto? {
    let kind = pigeonVar_list[0] as! String
    let remaining: Int64? = nilOrValue(pigeonVar_list[1])
    let reason: String? = nilOrValue(pigeonVar_list[2])

    return BiometricDecisionDto(
      kind: kind,
      remaining: remaining,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      remaining,
      reason,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BiometricResultDto.fromList(self.readValue() as! [Any?])
    case 130:
      return BiometricAvailabilityDto.fromList(self.readValue() as! [Any?])
    case 131:
      return BiometricDecisionDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BiometricResultDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BiometricAvailabilityDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BiometricDecisionDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricCoreHostApi {
  func availability() throws -> BiometricAvailabilityDto
  /// Prompt crudo, sin política. Útil para casos especiales; para login usar runSession.
  func authenticate(reason: String, allowPinFallback: Bool, completion: @escaping (Result<BiometricResultDto, Error>) -> Void)
  /// Ejecuta un intento de BiometricSession nativo (disponibilidad, prompt y política).
  func runSession(reason: String, maxAttempts: Int64, completion: @escaping (Result<BiometricDecisionDto, Error>) -> Void)
  /// Reinicia el contador de intentos de la sesión nativa.
  func resetSession() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricCoreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BiometricCoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricCoreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let availabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.availability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availabilityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.availability()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      availabilityChannel.setMessageHandler(nil)
    }
    /// Prompt crudo, sin política. Útil para casos especiales; para login usar runSession.
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        let allowPinFallbackArg = args[1] as! Bool
        api.authenticate(reason: reasonArg, allowPinFallback: allowPinFallbackArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    /// Ejecuta un intento de BiometricSession nativo (disponibilidad, prompt y política).
    let runSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.runSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        let maxAttemptsArg = args[1] as! Int64
        api.runSession(reason: reasonArg, maxAttempts: maxAttemptsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      runSessionChannel.setMessageHandler(nil)
    }
    /// Reinicia el contador de intentos de la sesión nativa.
    let resetSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.resetSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetSessionChannel.setMessageHandler { _, reply in
        do {
          try api.resetSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetSessionChannel.setMessageHandler(nil)
    }
  }
}
