// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.kodivex.biometric.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Espejo de BiometricResult.code. Se transporta como string para no acoplar
 * el enum de Dart al orden de los enums nativos.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BiometricResultDto (
  val code: String,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricResultDto {
      val code = pigeonVar_list[0] as String
      val reason = pigeonVar_list[1] as String?
      return BiometricResultDto(code, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      reason,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricAvailabilityDto (
  val type: String,
  val status: String,
  val isEnrolled: Boolean,
  val isLockedOut: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricAvailabilityDto {
      val type = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as String
      val isEnrolled = pigeonVar_list[2] as Boolean
      val isLockedOut = pigeonVar_list[3] as Boolean
      return BiometricAvailabilityDto(type, status, isEnrolled, isLockedOut)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      status,
      isEnrolled,
      isLockedOut,
    )
  }
}

/**
 * Espejo de BiometricPolicy.Decision. La política vive en nativo: Flutter solo
 * recibe la decisión ya tomada.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BiometricDecisionDto (
  val kind: String,
  val remaining: Long? = null,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricDecisionDto {
      val kind = pigeonVar_list[0] as String
      val remaining = pigeonVar_list[1] as Long?
      val reason = pigeonVar_list[2] as String?
      return BiometricDecisionDto(kind, remaining, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      remaining,
      reason,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricResultDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricAvailabilityDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricDecisionDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BiometricResultDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BiometricAvailabilityDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BiometricDecisionDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BiometricCoreHostApi {
  fun availability(): BiometricAvailabilityDto
  /** Prompt crudo, sin política. Útil para casos especiales; para login usar runSession. */
  fun authenticate(reason: String, allowPinFallback: Boolean, callback: (Result<BiometricResultDto>) -> Unit)
  /** Ejecuta un intento de BiometricSession nativo (disponibilidad, prompt y política). */
  fun runSession(reason: String, maxAttempts: Long, callback: (Result<BiometricDecisionDto>) -> Unit)
  /** Reinicia el contador de intentos de la sesión nativa. */
  fun resetSession()

  companion object {
    /** The codec used by BiometricCoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BiometricCoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BiometricCoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.availability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.availability())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.authenticate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val allowPinFallbackArg = args[1] as Boolean
            api.authenticate(reasonArg, allowPinFallbackArg) { result: Result<BiometricResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.runSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val maxAttemptsArg = args[1] as Long
            api.runSession(reasonArg, maxAttemptsArg) { result: Result<BiometricDecisionDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_core_flutter.BiometricCoreHostApi.resetSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetSession()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
